sudo: required

language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_2ba986d7921c_key -iv $encrypted_2ba986d7921c_iv -in helm-chart-deploy-key.enc -out helm-chart-deploy-key -d
- chmod 600 helm-chart-deploy-key
- cp helm-chart-deploy-key ~/.ssh/id_rsa
install:
- curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
- pip install --default-timeout=100 git+https://github.com/jupyterhub/chartpress.git
script:
- chartpress --commit-range ${TRAVIS_COMMIT_RANGE}

deploy:
  provider: script
  skip_cleanup: true
  script:
  - bash deploy.sh 
  on:
    branch:
    - master
