# will delete itself unless the helm upgrade process is aborted
{{ if .Values.prePuller.hook.enabled }}
{{ $name := print "hook-image-puller-" .Release.Name "-" .Release.Revision "-" .Release.Time.Seconds }}
{{ template "jupyterhub.imagePuller.daemonset" (dict "hook" true "name" $name "top" .) }}
{{- end }}
---
# will remain running and pull images on new nodes added to the cluster
{{ if .Values.prePuller.continuous.enabled }}
{{ template "jupyterhub.imagePuller.daemonset" (dict "hook" false "name" "continuous-image-puller" "top" .) }}
{{- end }}