{{ if .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: hub
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "persistentvolumeclaims"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: hub
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: hub
roleRef:
  kind: Role
  name: hub
  apiGroup: rbac.authorization.k8s.io
{{- end }}
